<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 * 
 * Template Name: Page with Tabs
 *
 * @package Genesis-Sitekick
 * @author  Hunter Williams
 * @license GPL-2.0+
 * @link    http://www.sitekick.com
 */

// This file handles pages, but only exists for the sake of child theme forward compatibility.

// Site footer elements.
add_filter( 'genesis_attr_entry', 'sitekick_entry_tabs' );

function sitekick_entry_tabs($attributes) {
  
  $attributes['id'] = 'entry-tabs';
  
  return $attributes;
}




//Custom fields
add_action( 'genesis_entry_header', 'sitekick_tabs_menu', 12 );

function sitekick_tabs_menu(){
	
	$op = '<ul class="tabs-menu">';
	$op .= '<a name="top"></a>';
	$op .= '<li><a href="#intro">Introduction</a></li>';
	$op .= '<li><a href="#key-concepts">Key Concepts</a></li>';
	$op .= '<li><a href="#tips-trade">Tips of the Trade</a></li>';
	$op .= '</ul>';
	
	print $op;
}



add_action( 'genesis_entry_content', 'sitekick_tabs_introduction', 8 );

function sitekick_tabs_introduction(){
	
	$introduction = get_field('introduction');
	
	$op = '<div id="intro" class="tab-content">';
	$op .= '<a name="intro"></a>';
	$op .= $introduction;
	$op .= '<ul class="section-controls">';
	$op .= '<li class="top"><a href="#top">Back to Top</a></li>';
	$op .= '<li class="next activate-tab"><a href="#key-concepts" data-tab-index="1">Key Concepts</a></li>';
	$op .= '</ul>';
	$op .= '</div>';
	
	print $op;
}

add_action( 'genesis_entry_content', 'sitekick_tabs_key_concepts', 9 );

function sitekick_tabs_key_concepts(){
	
	$keyConcepts = get_field('key_concepts');
	
	$op = '<div id="key-concepts" class="tab-content">';
	$op .= '<a name="key-concepts"></a>';
	$op .= $keyConcepts;
	$op .= '<ul class="section-controls">';
	$op .= '<li class="prev activate-tab"><a href="#intro" data-tab-index="0">Introduction</a></li>';
	$op .= '<li class="top"><a href="#top">Back to Top</a></li>';
	$op .= '<li class="next activate-tab"><a href="#tips-trade" data-tab-index="2">Tips of the Trade</a></li>';
	$op .= '</ul>';
	$op .= '</div>';
	
	print $op;
}

add_action( 'genesis_entry_content', 'sitekick_tabs_tips_of_the_trade', 10 );
add_filter('excerpt_length', 'sitekick_excerpt_length', 5);

function sitekick_tabs_tips_of_the_trade(){
	
	
	
	$tipsTradeId = get_field('tips_of_the_trade');
	
	
	
	$args = array (
		'posts_per_page'	=> 3,
		'cat' => $tipsTradeId,
		'post_status'  => 'publish',
		'orderby' => 'post_date',
		'order' => 'DESC',
	);
	
	$tipsTrade = new WP_Query( $args );
	
	if( !$tipsTradeId || !$tipsTrade->have_posts() ){
		$op = '<div id="tips-trade" class="tab-content disabled">';
		$op .= '<a name="tips-trade"></a>';
		$op .= '<h2>Tips of the Trade</h2>';
		$op .= '<p>There are no tips at this time.</p>';
		$op .= '</div>';
		
		print $op;
		
		return;
	} else {
		$op = '<div id="tips-trade" class="tab-content">';
		$op .= '<a name="tips-trade"></a>';
		$op .= '<h2>Tips of the Trade</h2>';
	}
	
	if ( $tipsTrade->have_posts() ) {
		
		while ( $tipsTrade->have_posts() ) {
			$tipsTrade->the_post();
			
			$op .= sprintf('
			<article class="type-tip"><header class="entry-header"><div class="entry-image"><a class="img-link" href="%s">%s</a></div></header><div class="entry-content" itemprop="text"><h2 class="entry-title" itemprop="headline">%s</h2><p>%s <footer class="entry-content-footer"><p class="entry-meta">%s | %s</p></footer></p></div></article>',
			get_permalink(),
			get_the_post_thumbnail(get_the_ID(),'thumbnail'),
			get_the_title(),
			get_the_excerpt(),
			do_shortcode('[post_readmore]'),
			do_shortcode('[post_date]')
			);
			
		}
		
		// Restore original Post Data
		wp_reset_postdata();
	
	} else {
		$op .= '<p>no posts found</p>';
	}
	$op .= '<ul class="section-controls">';
	$op .= '<li class="prev activate-tab"><a href="#key-concepts" data-tab-index="1">Key Concepts</a></li>';
	$op .= '<li class="top"><a href="#top">Back to Top</a></li>';
	$op .= '</ul></div>';
	
	print $op;

	
}

//Entry Footer

add_action( 'genesis_entry_footer', 'sitekick_tabs_footer');

function sitekick_tabs_footer(){
	printf( '<footer %s>%s</footer>', 
	genesis_attr( 'entry-footer' ),
	get_field('footer')
	);
}

genesis();