<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis-Sitekick
 * @author  Hunter Williams
 * @license GPL-2.0+
 * @link    http://www.sitekick.com
 */

// This file handles pages, but only exists for the sake of child theme forward compatibility.
genesis();

