<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 * 
 * Template Name: Page with Tabs
 *
 * @package Genesis-Sitekick
 * @author  Hunter Williams
 * @license GPL-2.0+
 * @link    http://www.sitekick.com
 */

// This file handles pages, but only exists for the sake of child theme forward compatibility.

// Site footer elements.
add_filter( 'genesis_attr_entry', 'sitekick_entry_tabs' );

function sitekick_entry_tabs($attributes) {
   //$attributes['class'] = $attributes['class'] . ' ' . 'entry-tabs';
   $attributes['id'] = 'entry-tabs';
  return $attributes;
}

//add entry footer
add_action( 'genesis_entry_footer', 'sitekick_entry_footer_markup_open', 5 );

function sitekick_entry_footer_markup_open() {
	printf( '<footer %s>', genesis_attr( 'entry-footer' ) );
}

add_action( 'genesis_entry_footer', 'sitekick_entry_footer_markup_close', 15 );

function sitekick_entry_footer_markup_close() {
	echo '</footer>';
}


//Custom fields
add_action( 'genesis_entry_content', 'sitekick_tabs_menu', 5 );

function sitekick_tabs_menu(){
	
	$op = '<ul class="tabs-menu">';
	$op .= '<li><a href="#intro">Introduction</a></li>';
	$op .= '<li><a href="#key-concepts">Key Concepts</a></li>';
	$op .= '<li><a href="#tips-trade">Tips of the Trade</a></li>';
	$op .= '</ul>';
	
	print $op;
}



add_action( 'genesis_entry_content', 'sitekick_tabs_introduction', 8 );

function sitekick_tabs_introduction(){
	
	$introduction = get_field('introduction');
	
	$op = '<div id="intro" class="tab-content">';
	$op .= '<a name="intro"></a>';
	$op .= $introduction;
	$op .= '</div>';
	
	print $op;
}

add_action( 'genesis_entry_content', 'sitekick_tabs_key_concepts', 9 );

function sitekick_tabs_key_concepts(){
	
	$keyConcepts = get_field('key_concepts');
	
	
	$op = '<div id="key-concepts" class="tab-content">';
	$op .= '<a name="key-concepts"></a>';
	$op .= $keyConcepts;
	$op .= '</div>';
	
	print $op;
}

add_action( 'genesis_entry_content', 'sitekick_tabs_tips_of_the_trade', 10 );

function sitekick_tabs_tips_of_the_trade(){
	
	//$tipsTrade = get_field('tips_of_the_trade');
	
	$op = '<div id="tips-trade" class="tab-content">';
	$op .= 'tba';
	$op .= '</div>';
	
	print $op;
}

//Entry Footer

add_action( 'genesis_entry_footer', 'sitekick_tabs_footer', 12 );

function sitekick_tabs_footer(){
	
/*
	$footer = get_field('footer');
	
	$op = '<div id="tips-trade" class="tab-content">';
	$op .= $footer
	$op .= '</div>';
*/
	
	print get_field('footer');
}


genesis();
